---
title: Martin Zähringer
timezone: UTC
collections:
  photographs:
    title: Photographs
    output: true
  publishing:
    title: Publishing
    output: true
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: false
url: https://www.martinzahringer.com
description: London-based photographer
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Martin Zähringer
email: 
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  instagram: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: martin-zahringer.imgix.net
